#!/usr/bin/env python3

import os, sys, shutil

if __name__ == '__main__':
    if os.geteuid() != 0:
        print('Checking if installation files are present')
        allFilesPresent = True
        if not os.path.isfile('./htpc-browser-launcher.cfg'):
            print('htpc-browser-launcher.cfg could not be found')
            allFilesPresent = False
        if not os.path.isfile('./htpc-browser-launcher.py'):
            print('htpc-browser-launcher.py could not be found')
            allFilesPresent = False
        if not os.path.isfile('./.keynavrc'):
            print('.keynavrc could not be found')
            allFilesPresent = False
        if not allFilesPresent:
            print('No changes made')
            print('Exiting')
            sys.exit(0)
        if os.path.isdir('./.htpc-browser-launcher'):
            shutil.rmtree('./.htpc-browser-launcher')
        os.mkdir('./.htpc-browser-launcher')
        print('Installing HTPC Browser Launcher')
        shutil.move("./htpc-browser-launcher.cfg", "./.htpc-browser-launcher/htpc-browser-launcher.cfg")
        shutil.move("./htpc-browser-launcher.py", "./.htpc-browser-launcher/htpc-browser-launcher.py")
        os.chmod("./.htpc-browser-launcher/htpc-browser-launcher.py", 0o755)
        print('HTPC Browser Launcher was successfully installed.')
    else:
        print('Run this install script without using sudo')
        print('No changes made')
        print('Exiting')
